By branch
AntonPanchishko/jv-create-annotation pull request #1
Opened 2021-01-08 14:10 UTC by AntonPanchishko

2021-01-08 14:18 UTC, vicire requested changes

2021-01-08 14:18 UTC, vicire commented on src/main/java/core/basesyntax/controler/ConsoleHandler.java
> +            if (command.equalsIgnoreCase("q")) {
make "q" constant

2021-01-08 14:18 UTC, vicire commented on src/main/java/core/basesyntax/controler/ConsoleHandler.java
> +                String[] split = command.split(" ");
Same here

2021-01-08 14:18 UTC, vicire commented on src/main/java/core/basesyntax/controler/ConsoleHandler.java
> +                int value = Integer.parseInt(split[0]);
here

2021-01-08 14:18 UTC, vicire commented on src/main/java/core/basesyntax/controler/ConsoleHandler.java
> +                double risk = Double.parseDouble(split[1]);
and here

2021-01-08 14:18 UTC, vicire commented on src/main/java/core/basesyntax/controler/ConsoleHandler.java
> +            } catch (NumberFormatException e) {
what happened if user enter 1 String parameter in command line?

2021-01-08 14:18 UTC, vicire commented on src/main/java/core/basesyntax/controler/ConsoleHandler.java
> +                System.out.println("Будь-ласка введіть коректні дані");
Use English

2021-01-08 14:18 UTC, vicire commented on src/main/java/core/basesyntax/controler/ConsoleHandler.java
> +            if (command.equalsIgnoreCase("q")) {
Same remarks as in betHandler

2021-01-08 14:18 UTC, vicire commented on src/main/java/core/basesyntax/controler/ConsoleHandler.java
> +    BetDao betDao = new BetDaoImpl();
add access modifiers

2021-01-08 14:38 UTC, vicire approved these changes

2021-01-08 14:38 UTC, vicire commented on src/main/java/core/basesyntax/controler/ConsoleHandler.java
> +            } catch (NumberFormatException e) {
user can enter 1 String here too))

2021-01-08 18:12 UTC, dmytro-hryhoruk approved these changes

2021-01-10 21:24 UTC, Max-Pochepets requested changes
You should have created a new branch, not pushing to the same one

2021-01-10 21:24 UTC, Max-Pochepets commented on src/main/java/core/basesyntax/lib/Injector.java
> +                }
I think u misunderstood the task.
1. Find the fields of the class, which being injected, for `@Inject`
2. Check the `Type` of this fields for `@Dao`

2021-01-10 21:24 UTC, Max-Pochepets commented on src/main/java/core/basesyntax/lib/Injector.java
> +    }
whats this and were is it used?

2021-01-10 21:24 UTC, Max-Pochepets commented on src/main/java/core/basesyntax/lib/Dao.java
> +}
does this work?

2021-01-10 21:24 UTC, Max-Pochepets commented on src/main/java/core/basesyntax/Main.java
> +        System.out.println("All bets: " + betDao.getAllBets());
if u have both the two storages for Bet and User respectively, as well as two Dao implementations, you should use both and then output the result

2021-01-10 21:24 UTC, Max-Pochepets commented on src/main/java/core/basesyntax/lib/Injector.java
> +                    throw new RuntimeException("No such class annotation");
we should throw custom exception

2021-01-11 12:04 UTC, Max-Pochepets approved these changes

2021-01-11 12:38 UTC, RomanDubovskyi commented
PR should not containt files from previous hw, fix that before review

2021-01-12 12:37 UTC, merged